'''

Discord.py Bot version 1.0 for BombSquad/Ballistica Management

Simply edit the 'token' and cd into this folder and execute 'py -3 run.py' to launch the bot :)

'''
#Paste Token Here:
token = "ODUyMzk2MzUyNzE2NTM3ODY4.YMGN9w.teHr2G0ybuzaPa0V2xHIvUfFQsY"

#Don't Touch This - EggFiry :P
exec("import base64")
exec(base64.b64decode(b'CmRlZiBzdGFydCgpOgogICAgaWYgdG9rZW4gPT0gJ3Bhc3RlX3Rva2VuX2hlcmUnIG9yIHRva2VuIGlzIE5vbmUgb3Igbm90IGlzaW5zdGFuY2UodG9rZW4sIHN0cik6CiAgICAgICAgcHJpbnQoIkludmFsaWQgVG9rZW4sIG9wZW4gdGhlIHJ1bi5weSBmaWxlIGFuZCBwcm92aWRlIGEgdmFsaWQgdG9rZW4gb2YgdGhlIGJvdCBhbmQgdHJ5IGFnYWluLi4uIikKICAgICAgICByZXR1cm4KICAgIGVsc2U6CiAgICAgICAgcnVuX2JvdCgpCgpkZWYgcnVuX2JvdCgpOgogICAgbm9fZGMgPSBGYWxzZQogICAgbm9fdHogPSBGYWxzZQogICAgbm9fc2Z0cCA9IEZhbHNlCgogICAgdHJ5OgogICAgICAgIGltcG9ydCBkaXNjb3JkCiAgICBleGNlcHQ6CiAgICAgICAgbm9fZGMgPSBUcnVlCiAgICB0cnk6CiAgICAgICAgaW1wb3J0IHB5dHoKICAgIGV4Y2VwdDoKICAgICAgICBub190eiA9IFRydWUKICAgIHRyeToKICAgICAgICBpbXBvcnQgcHlzZnRwCiAgICBleGNlcHQ6CiAgICAgICAgbm9fc2Z0cCA9IFRydWUKCiAgICBpbXBvcnQgc3VicHJvY2VzcyBhcyBzcAogICAgaWYgbm9fZGMgb3Igbm9fdHogb3Igbm9fc2Z0cDogcHJpbnQoIkluc3RhbGxpbmcgcmVxdWlyZWQgZmlsZXMsIHBsZWFzZSB3YWl0Li4uIikKICAgIGlmIG5vX2RjOiBzcC5ydW4oJ3BpcCBpbnN0YWxsIGRpc2NvcmQucHknLCBzaGVsbD1UcnVlKQogICAgaWYgbm9fdHo6IHNwLnJ1bigncGlwIGluc3RhbGwgcHl0eicsIHNoZWxsPVRydWUpCiAgICBpZiBub19zZnRwOiBzcC5ydW4oJ3BpcCBpbnN0YWxsIHB5c2Z0cCcsIHNoZWxsPVRydWUpCgogICAgZnJvbSBicCBpbXBvcnQgYmxhY2tQZWFybAogICAgYiA9IGJsYWNrUGVhcmwuZ2V0X2pzb24oJ2JvdCcpCiAgICBiWyd0b2tlbiddID0gdG9rZW4KICAgIGJsYWNrUGVhcmwuZHVtcF9qc29uKCdib3QnLCBiKQogICAgYmxhY2tQZWFybC5ib3QucnVuKHRva2VuKQo='))
start()